import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createHash, randomUUID } from 'node:crypto';
import { URL } from 'node:url';
import { WorkflowIntentSchema, type EventEnvelope, type ProcedureGraph, type WorkflowIntent } from '@vision-codef/contracts';
import { DevelopmentStore, type CaptureSession, type DeploymentRun, type Workflow } from './store.js';
import { evaluatePaperCraneObservation, PAPER_CRANE_POLICY } from './paper-crane.js';
import type { DeviationState } from '@vision-codef/workflow-engine';

const port = Number(process.env.PORT ?? 4000);
const store = new DevelopmentStore();
const companyId = process.env.DEMO_COMPANY_ID ?? '00000000-0000-7000-8000-000000000001';
const now = () => new Date().toISOString();
const id = () => randomUUID();
const liveKitConfigured = Boolean(process.env.LIVEKIT_API_KEY && process.env.LIVEKIT_API_SECRET && process.env.LIVEKIT_URL);
const paperStates = new Map<string, DeviationState>();
const interventions = new Map<string, Record<string, unknown>>();
function deploymentView(run: DeploymentRun) { const workflow = getWorkflow(run.workflowId); return { ...run, status: run.status === 'active' ? 'monitoring' : run.status, totalSteps: workflow.graph?.steps.length ?? 0, currentInstruction: workflow.graph?.steps[run.currentStep]?.instruction, intervention: interventions.get(run.id) }; }

function classify(text: string): WorkflowIntent {
  const value = text.toLowerCase();
  const goldenCues = ['teach', 'procedure', 'maintenance', 'training', 'steps', 'repair', 'assembly', 'inspection', 'demonstration', 'how to'];
  const cameraCues = ['detect', 'alert', 'camera', 'premises', 'after hours', 'zone', 'person', 'vehicle', 'notify', 'cctv', 'event'];
  const goldenHits = goldenCues.filter((cue) => value.includes(cue)).length;
  const cameraHits = cameraCues.filter((cue) => value.includes(cue)).length;
  const family = goldenHits === cameraHits ? 'ambiguous' : goldenHits > cameraHits ? 'golden_run' : 'camera_automation';
  const confidence = family === 'ambiguous' ? 0.5 : Math.min(0.98, 0.55 + Math.abs(goldenHits - cameraHits) / Math.max(goldenHits + cameraHits, 1) * 0.4);
  return WorkflowIntentSchema.parse({ family, confidence, rationale: family === 'ambiguous' ? 'The request needs one workflow-family choice.' : `Matched ${family === 'golden_run' ? goldenHits : cameraHits} workflow cue(s).`, extractedGoal: text.trim(), mentionedDevices: [], mentionedConditions: [], mentionedActions: [], missingCriticalFields: family === 'ambiguous' ? ['workflow family'] : [] });
}

function graphFor(workflowId: string): ProcedureGraph {
  const start = id(); const folded = id(); const complete = id(); const first = id(); const second = id();
  return { id: workflowId, version: 1, published: false, states: [{ id: start, label: 'Flat and aligned', predicates: ['four corners visible', 'bottom edge aligned'] }, { id: folded, label: 'Triangle fold', predicates: ['top corner meets bottom corner'] }, { id: complete, label: 'Complete', predicates: ['center crease is flat'] }], steps: [{ id: first, ordinalHint: 0, title: 'Set the paper square', instruction: 'Place the paper with the white side up and align the bottom edge with the mat.', observedAction: 'Paper boundary and four corners are visible.', evidenceRefs: [], provenance: ['EXPERT_ASSERTION', 'PUBLISHED_REQUIREMENT'], startState: [start], expectedAction: ['place paper', 'align bottom edge', '*'], endState: [folded], allowableVariations: ['Small rotation under 5 degrees'], deviationRules: ['Request better visibility if fewer than four corners are visible.'], recoveryTransitions: [], confidence: 0.98 }, { id: second, ordinalHint: 1, title: 'Fold the top corner down', instruction: 'Bring the top corner down to meet the bottom corner, then crease firmly.', observedAction: 'Top corner moves toward the bottom corner.', evidenceRefs: [], provenance: ['EXPERT_ASSERTION', 'SENSOR_OBSERVATION', 'PUBLISHED_REQUIREMENT'], startState: [folded], expectedAction: ['fold top corner', 'crease', '*'], endState: [complete], allowableVariations: ['Corner alignment within configured tolerance'], deviationRules: ['Interrupt if the wrong corner moves toward the bottom edge.'], recoveryTransitions: [first], confidence: 0.91 }], contentHash: undefined };
}

async function readJson(request: IncomingMessage): Promise<Record<string, unknown>> { let raw = ''; for await (const chunk of request) raw += chunk; if (!raw) return {}; try { return JSON.parse(raw) as Record<string, unknown>; } catch { throw new HttpError(400, 'VALIDATION_FAILED', 'Request body must be valid JSON.'); } }
class HttpError extends Error { constructor(readonly status: number, readonly code: string, message: string) { super(message); } }
function send(response: ServerResponse, status: number, data: unknown, traceId = id()) { response.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,PATCH,OPTIONS', 'access-control-allow-headers': 'content-type, authorization, x-company-id, x-member-id, idempotency-key' }); response.end(JSON.stringify({ data, traceId, schemaVersion: '0.1' })); }
function event(eventType: string, payload: Record<string, unknown>, workflowId?: string, sessionId?: string, runId?: string) { const value: EventEnvelope = { eventId: id(), schemaVersion: '0.1', companyId, workflowId, sessionId, runId, source: 'api', occurredAt: now(), traceId: id(), eventType, payload }; store.events.push(value); return value; }
function getWorkflow(value: string) { const workflow = store.workflows.get(value); if (!workflow) throw new HttpError(404, 'NOT_FOUND', 'Workflow was not found.'); return workflow; }
function getCapture(value: string) { const capture = store.captures.get(value); if (!capture) throw new HttpError(404, 'NOT_FOUND', 'Capture session was not found.'); return capture; }
function getDeployment(value: string) { const run = store.deployments.get(value); if (!run) throw new HttpError(404, 'NOT_FOUND', 'Deployment run was not found.'); return run; }

async function route(request: IncomingMessage, response: ServerResponse) {
  const traceId = id(); const url = new URL(request.url ?? '/', `http://${request.headers.host ?? 'localhost'}`); const method = request.method ?? 'GET';
  if (method === 'OPTIONS') { send(response, 204, null, traceId); return; }
  if (url.pathname === '/health' && method === 'GET') { send(response, 200, { status: 'ok', service: 'api', time: now() }, traceId); return; }
  const path = url.pathname.startsWith('/api/v1/') ? url.pathname.slice(4) : url.pathname;
  if (!path.startsWith('/v1/')) throw new HttpError(404, 'NOT_FOUND', 'Route was not found.');
  const parts = path.split('/').filter(Boolean).slice(1); const payload = ['POST', 'PATCH', 'PUT'].includes(method) ? await readJson(request) : {};
  if (parts[0] === 'workflows' && parts[1] === 'intent' && method === 'POST') { send(response, 200, classify(String(payload.brief ?? payload.text ?? '')), traceId); return; }
  if (parts[0] === 'workflows' && parts.length === 1 && method === 'GET') { send(response, 200, [...store.workflows.values()], traceId); return; }
  if (parts[0] === 'workflows' && parts.length === 1 && method === 'POST') { const objective = String(payload.brief ?? payload.objective ?? payload.message ?? '').trim(); if (!objective) throw new HttpError(400, 'VALIDATION_FAILED', 'brief is required.'); const intent = classify(objective); if (intent.family === 'ambiguous') { send(response, 200, { intent, requiresClarification: true }, traceId); return; } const workflow: Workflow = { id: id(), companyId, title: objective.slice(0, 72), family: intent.family, objective, status: 'Draft', createdAt: now(), updatedAt: now() }; store.workflows.set(workflow.id, workflow); event('workflow.created', { intent }, workflow.id); send(response, 201, { ...workflow, intent, stage: 'train', description: objective }, traceId); return; }
  if (parts[0] === 'workflows' && parts.length === 2 && method === 'GET') { const workflow = getWorkflow(parts[1]!); send(response, 200, { ...workflow, stage: workflow.status === 'Published' ? 'deploy' : 'train', description: workflow.objective }, traceId); return; }
  if (parts[0] === 'workflows' && parts[2] === 'capture-sessions' && parts.length === 3 && method === 'POST') { const workflow = getWorkflow(parts[1]!); if (workflow.family !== 'golden_run') throw new HttpError(409, 'CONFLICT', 'Only Golden Run workflows can capture.'); const capture: CaptureSession = { id: id(), workflowId: workflow.id, companyId, state: 'preparing' }; store.captures.set(capture.id, capture); event('capture.created', { state: capture.state }, workflow.id, capture.id); send(response, 201, { ...capture, connectionStatus: 'disconnected', roomName: `company-${companyId}-workflow-${workflow.id}` }, traceId); return; }
  if (parts[0] === 'capture-sessions' && parts.length === 2 && method === 'GET') { const capture = getCapture(parts[1]!); send(response, 200, { ...capture, connectionStatus: capture.state === 'active' ? 'connecting' : 'disconnected' }, traceId); return; }
  if (parts[0] === 'capture-sessions' && parts[2] === 'start' && parts.length === 3 && method === 'POST') { const capture = getCapture(parts[1]!); capture.state = 'active'; capture.startedAt ??= now(); event('capture.started', { state: capture.state }, capture.workflowId, capture.id); send(response, 200, { ...capture, connectionStatus: 'connecting', roomName: `company-${companyId}-workflow-${capture.workflowId}` }, traceId); return; }
  if (parts[0] === 'capture-sessions' && parts[2] === 'stop' && parts.length === 3 && method === 'POST') { const capture = getCapture(parts[1]!); capture.state = 'processing'; capture.endedAt = now(); const workflow = getWorkflow(capture.workflowId); workflow.status = 'Processing'; workflow.updatedAt = now(); event('capture.ended', { state: capture.state }, capture.workflowId, capture.id); send(response, 200, { ...capture, connectionStatus: 'disconnected', mediaAsset: { id: id(), state: liveKitConfigured ? 'available' : 'pending', objectKey: liveKitConfigured ? `companies/${companyId}/captures/${capture.id}/egress.mp4` : undefined } }, traceId); return; }
  if (parts[0] === 'capture-sessions' && parts[2] === 'monitor' && parts.length === 3 && method === 'GET') { const capture = getCapture(parts[1]!); const configured = liveKitConfigured; send(response, 200, { sessionId: capture.id, roomName: `company-${companyId}-workflow-${capture.workflowId}`, serverUrl: process.env.LIVEKIT_URL ?? '', viewerToken: '', status: configured ? 'waiting' : 'disconnected', audioConnected: false, videoConnected: false, reason: configured ? 'Waiting for phone publisher.' : 'LiveKit credentials are not configured.' }, traceId); return; }
  if (parts[0] === 'capture-sessions' && parts[2] === 'processing' && parts.length === 3 && method === 'GET') { const capture = getCapture(parts[1]!); const done = capture.state === 'completed'; send(response, 200, { sessionId: capture.id, status: done ? 'completed' : 'queued', progress: done ? 100 : 10, message: done ? 'Procedure graph draft is ready.' : 'Processing is waiting for the durable worker.', graphId: done ? getWorkflow(capture.workflowId).graph?.id : undefined }, traceId); return; }
  if (parts[0] === 'workflows' && parts[2] === 'procedure-graph' && parts.length === 3 && method === 'GET') { const workflow = getWorkflow(parts[1]!); workflow.graph ??= graphFor(workflow.id); send(response, 200, workflow.graph, traceId); return; }
  if (parts[0] === 'workflows' && parts[2] === 'procedure-graph' && parts.length === 3 && method === 'PATCH') { const workflow = getWorkflow(parts[1]!); const graph = payload.graph as ProcedureGraph | undefined; if (!graph) throw new HttpError(400, 'VALIDATION_FAILED', 'graph is required.'); workflow.graph = { ...graph, published: false }; workflow.status = 'Needs Review'; workflow.updatedAt = now(); event('procedure.draft.updated', { version: workflow.graph.version }, workflow.id); send(response, 200, workflow.graph, traceId); return; }
  if (parts[0] === 'workflows' && parts[2] === 'procedure-graph' && parts[3] === 'publish' && parts.length === 4 && method === 'POST') { const workflow = getWorkflow(parts[1]!); const graph = (payload.graph as ProcedureGraph | undefined) ?? workflow.graph ?? graphFor(workflow.id); workflow.graph = { ...graph, published: true, contentHash: createHash('sha256').update(JSON.stringify(graph)).digest('hex') }; workflow.status = 'Published'; workflow.updatedAt = now(); event('procedure.published', { version: workflow.graph.version, contentHash: workflow.graph.contentHash }, workflow.id); send(response, 200, workflow.graph, traceId); return; }
  if (parts[0] === 'workflows' && parts[2] === 'deployments' && parts.length === 3 && method === 'POST') { const workflow = getWorkflow(parts[1]!); if (workflow.status !== 'Published') throw new HttpError(412, 'PRECONDITION_FAILED', 'A published workflow is required before deployment.'); const run: DeploymentRun = { id: id(), workflowId: workflow.id, companyId, status: 'ready', currentStep: 0, deviations: [] }; store.deployments.set(run.id, run); event('deployment.created', { status: run.status }, workflow.id, undefined, run.id); paperStates.set(run.id, { status: 'clear' }); send(response, 201, deploymentView(run), traceId); return; }
  if (parts[0] === 'deployments' && parts.length === 2 && method === 'GET') { const run = getDeployment(parts[1]!); const workflow = getWorkflow(run.workflowId); send(response, 200, deploymentView(run), traceId); return; }
  if (parts[0] === 'deployments' && parts[2] === 'observations' && parts.length === 3 && method === 'POST') { const run = getDeployment(parts[1]!); if (!paperStates.has(run.id)) paperStates.set(run.id, { status: 'clear' }); let result; try { result = evaluatePaperCraneObservation(paperStates.get(run.id), payload); } catch (error) { throw new HttpError(400, 'VALIDATION_FAILED', error instanceof Error ? error.message : 'Invalid paper-crane observation.'); } paperStates.set(run.id, result.state); if (result.decision.type === 'INTERRUPT') { run.status = 'active'; run.deviations.push({ id: id(), state: 'confirmed', severity: 'stop' }); interventions.set(run.id, { title: 'Wrong fold detected', detail: result.decision.reason, recoveryStepId: result.decision.recovery.id, confidence: 0.9, persistenceMs: PAPER_CRANE_POLICY.expected.persistenceMs }); event('deviation.interrupted', { decision: result.decision.type, reason: result.decision.reason }, run.workflowId, undefined, run.id); } send(response, 200, { ...deploymentView(run), decision: result.decision.type, decisionReason: result.decision.reason }, traceId); return; }
  if (parts[0] === 'deployments' && parts[2] === 'recovery' && parts.length === 3 && method === 'POST') { const run = getDeployment(parts[1]!); if (run.status !== 'active' || !interventions.has(run.id)) throw new HttpError(409, 'CONFLICT', 'No approved recovery is currently required.'); run.status = 'completed'; run.currentStep += 1; run.deviations.push({ id: id(), state: 'resolved', severity: 'stop' }); interventions.delete(run.id); paperStates.set(run.id, { status: 'resolved' }); event('deviation.resolved', { recoveryStepId: String(payload.recoveryStepId ?? '') }, run.workflowId, undefined, run.id); send(response, 200, deploymentView(run), traceId); return; }
  if (parts[0] === 'events' && method === 'GET') { send(response, 200, store.events.filter((value) => value.companyId === companyId), traceId); return; }
  throw new HttpError(404, 'NOT_FOUND', 'Route was not found.');
}

const server = createServer(async (request, response) => { try { await route(request, response); } catch (error) { const status = error instanceof HttpError ? error.status : 500; const code = error instanceof HttpError ? error.code : 'INTERNAL_ERROR'; const message = error instanceof Error ? error.message : 'Unexpected server error.'; send(response, status, { error: { code, message, traceId: id() } }); } });
server.listen(port, () => console.log(`Vision Codef API listening on http://localhost:${port}`));
process.on('SIGTERM', () => server.close());

