export type ReviewLanguage = 'en' | 'ms' | 'zh-TW';
/** UI copy only. Never silently translate the technician's evidence or instructions. */
export const reviewCopy = {
  en: {
    title: 'Review your recording',
    step: 'Step name',
    instruction: 'What should the junior do?',
    tip: 'What should a junior watch out for? (optional)',
    extra: 'Add checks or reference material',
    check: 'How do you know it is correct? (optional)',
    references: 'Documentation / reference (optional)',
    notes: 'Notes at a specific moment',
    note: 'Note',
    why: 'What matters here, and why?',
    adjust: 'Adjust step',
    next: 'Mark reviewed and next',
    reviewed: 'Reviewed',
    save: 'Save draft',
    saved: 'Saved',
    unsaved: 'Unsaved changes — select Save draft',
    publish: 'Publish reviewed procedure',
    original: 'Original AI suggestion',
    language: 'Review language',
    hint: 'Use your workshop’s part names and language. Changing this setting does not translate existing content.',
    progress: 'actions reviewed · AI draft, not verified instructions. Timing is approximate.',
  },
  ms: {
    title: 'Semak rakaman anda',
    step: 'Nama langkah',
    instruction: 'Apakah yang perlu dilakukan oleh juruteknik baharu?',
    tip: 'Apakah yang perlu diberi perhatian? (Pilihan)',
    extra: 'Tambah semakan atau bahan rujukan',
    check: 'Bagaimanakah anda tahu hasilnya betul? (Pilihan)',
    references: 'Dokumen / rujukan (pilihan)',
    notes: 'Nota pada masa tertentu',
    note: 'Nota',
    why: 'Apakah yang penting di sini, dan mengapa?',
    adjust: 'Laraskan langkah',
    next: 'Tandakan telah disemak dan seterusnya',
    reviewed: 'Telah disemak',
    save: 'Simpan draf',
    saved: 'Disimpan',
    unsaved: 'Perubahan belum disimpan — pilih Simpan draf',
    publish: 'Terbitkan prosedur yang telah disemak',
    original: 'Cadangan asal AI',
    language: 'Bahasa semakan',
    hint: 'Gunakan nama komponen dan bahasa di tempat kerja anda. Tetapan ini tidak menterjemah kandungan sedia ada.',
    progress: 'tindakan disemak · Draf AI, bukan arahan yang disahkan. Masa adalah anggaran.',
  },
  'zh-TW': {
    title: '檢視您的錄影',
    step: '步驟名稱',
    instruction: '新進技術人員應該怎麼做？',
    tip: '新進技術人員需要注意什麼？（選填）',
    extra: '新增檢查方式或參考資料',
    check: '如何確認操作正確？（選填）',
    references: '文件／參考資料（選填）',
    notes: '特定時間點的筆記',
    note: '筆記',
    why: '這裡要注意什麼？為什麼？',
    adjust: '調整步驟',
    next: '標記已檢視並前往下一步',
    reviewed: '已檢視',
    save: '儲存草稿',
    saved: '已儲存',
    unsaved: '有尚未儲存的變更 — 請選擇「儲存草稿」',
    publish: '發布已檢視的作業程序',
    original: 'AI 原始建議',
    language: '檢視語言',
    hint: '請使用現場慣用的零件名稱與語言。切換設定不會翻譯既有內容。',
    progress: '個動作已檢視 · AI 草稿，並非已確認的操作指示。時間為估計值。',
  },
};
